aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:p33restoresds-final-snapshot  --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:p33sdsrds01  --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:p33sdsrds01-final-snapshot  --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:p33sdsrds1-final-snapshot  --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:p33sdsrestore-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"




--tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"QA\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"


aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:q33sdsrds1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"QA\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:q33sossdb01-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"QA\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:q33sossdb0101616 --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"QA\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:q33sossdb02 --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"QA\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"




--tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"


aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:sdc-uat-int-db1-final-1 --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:sdc-uat-int-db1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:sdc-uat-int-db1-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:sdcint-uat-1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:sdcint-uat-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:sigue-international-db-restore --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:sigue-uat2-db --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-joomla-2010021602 --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-uat-2-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-uat-db01-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-uat-db1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-uat-db1-final-snapshot-20200618 --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-uat-db1-final-snapshot-delete --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-uat-final-snapshot-202003021104 --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-uat-to-prod --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcomuat-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguev2-uat-db1-before-php-upgrade --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguev2-uat-db1-spanishversion --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguev2-prod-db1-20200717-uat-restore --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguev2-prod-db1-20200831 --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-prod-db1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-prod-db1-final-snapshot-20200618 --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:siguedotcom-prod-db1-restore-uat-20200302 --tags "[{\"Key\": \"Application\",\"Value\": \"SigueDotCom\"},{\"Key\": \"Environment\",\"Value\": \"Production\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33restoresds-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsappelbdev-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsdb1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsrds01-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsrds01final --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsrds1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsrestore-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsrestore-final-snapshot-joomla-site --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsrestore1-final-snapshot --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"
aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:t33sdsrestore201903261455 --tags "[{\"Key\": \"Application\",\"Value\": \"SiguePay\"},{\"Key\": \"Environment\",\"Value\": \"UAT\"},{\"Key\": \"Function\",\"Value\": \"RDS_Database\"}]"




aws rds add-tags-to-resource --resource-name arn:aws:rds:us-east-1:765032730250:snapshot:wordpress-db01-final-snapshot 